module.exports={
    port:3000,
    db:"pro_manager",
    crypto_key:"123456fedcba",
    loginSucess:"登录成功！",
    registerSucess:"注册成功！",
    deleteSucess:"删除成功！",
    findSucess:"查找成功！",
    saveSucess:"保存成功！",
    updateSucess:"更新成功！",
    TokenDuration:1000*60*60*24,
    pageCount:5,
}
